version: '3'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    command: sleep infinity
    network_mode: service:db
    volumes:
      - ..:/workspace:cached
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
